### ISSUE TITLE
Plan for more components?

### ISSUE THREAD

**Issue by vickOnRails** [facebookincubator/infima#100]
Hey guys. Just stumbled on Infima while working with Docusaurus. Awesome jobs you guys are doing here. 

But I have a use case that is rather uncommon and requires form components (Input, switches, etc). 

I'm sure there are plans for styling more of these components but I couldn't find them. 

Could someone give me some heads up? 

Thanks a lot, guys🙏

**Comment by slorber** [comment]
Thanks

We'll have to discuss this internally but I don't think the goal of Infima is to provide an exhaustive list of UI components. Infima is meant to be used for content-centric websites, and forms is another different use-case.

Let's track the future of Infima on this Roadmap issue: https://github.com/facebookincubator/infima/issues/93
