### ISSUE TITLE
Documentation for Spacing

### ISSUE THREAD

**Issue by qin-guan** [facebookincubator/infima#105]
Hey there, thanks for the great work on the library. 

Are there plans to add documentation for [Spacing](https://infima.dev/docs/layout/spacing), as it is currently marked as TODO, and would the team be open to PRs regarding it?

**Comment by slorber** [comment]
Thanks.

I think a doc PR to add spacing would be welcome yes, @yangshun ?

**Comment by yangshun** [comment]
Yes it'd be welcome! You can take inspiration from https://getbootstrap.com/docs/5.0/utilities/spacing/

**Comment by qin-guan** [comment]
i'll close this issue since it has been merged already, thanks very much! :)
