### ISSUE TITLE
Update of spacing page on website

### ISSUE THREAD

**Issue by mechamobau** [facebookincubator/infima#119]
I needed a solution for spaces using infima, searching in the official website the [page that refers to this section has content with `TODO` only](https://infima.dev/docs/layout/spacing). This page was created in this repository (https://github.com/facebookincubator/infima/pull/108), but has not yet been added to the site, does the project have any plans to update that page?

**Comment by yangshun** [comment]
I'll deploy the updated site later.

**Comment by slorber** [comment]
@yangshun isn't infima.dev wired to the Netlify deployment? Any reason for that?

Because the Netlify deployment seems up to date: https://infima.netlify.app/docs/layout/spacing

**Comment by yangshun** [comment]
Oh I think infima.dev is pointing to the GH pages

**Comment by slorber** [comment]
Are GH pages currently deployed manually?

Probably worth leaving GH pages behind and make Cloudflare target `infima.netlify.app`, cc @JoelMarcey

**Comment by JoelMarcey** [comment]
You can use GitHub Actions to deploy automatically. Or the site can be moved solely to Netlify. I think either would be fine.

**Comment by slorber** [comment]
I'd rather move it to Netlify as we use it for previews. @yangshun are you ok with that?

**Comment by yangshun** [comment]
Yep definitely.

Regards,
Yangshun

**Comment by slorber** [comment]
done

spacing doc is online here now: https://infima.dev/docs/layout/spacing
