### ISSUE TITLE
chevron level on different nesting

### ISSUE THREAD

**Issue by endiliey** [facebookincubator/infima#12]
https://github.com/reduxjs/redux/pull/3635#issuecomment-557927225

> Actually, the bigger problem there is the chevron is quite visually similar to the one below it, despite them being a different levels:
![image](https://user-images.githubusercontent.com/17883920/69531679-dc1b8400-0fa6-11ea-9688-65d9884c2277.png)
> So, whatever styling is done there should also apply to the expandability indicator.

**Comment by yangshun** [comment]
Don't think this is an issue.
