### ISSUE TITLE
Dark Mode does not follow System theme

### ISSUE THREAD

**Issue by AJAYK-01** [facebookincubator/infima#184]
## Context
- Many websites like Youtube and Github automatically switch to Dark Mode if the system is in Dark Mode, without needing to explicitly switch.
- I noticed that websites built with Infima, including https://infima.dev/docs does not follow this convention.
- I think an auto dark mode by detecting the system settings would be a good minor enhancement to the user experience as most of the OSes now support System wide Dark mode options.

## Possible Solution
I saw this [Article](https://www.section.io/engineering-education/watch-for-system-dark-mode-using-js-css/) which seems to be related to detecting the system theme and switching to it using Javascript.

**Comment by slorber** [comment]
Hey

You can add that `respectPrefersColorScheme: true` config if you want, but wonder why do you care that much? 😅
