### ISSUE TITLE
Use of `background` property to set background color clobbers other background properties

### ISSUE THREAD

**Issue by reefdog** [facebookincubator/infima#198]
I've run into some trouble customizing a Docusaurus site due to Infima's pattern of specifying the entire `background` property for elements when it's actually just targeting the `background-color`.

The specific case I'm bumping against is [here](https://github.com/facebookincubator/infima/blob/8c592e4fad80d410fcb9ffb132e6b2efc70c9db4/packages/core/styles/components/menu.pcss#L132), but I did a quick search and see many other instances where the `background` property is being set to just a color.

**Problem:** This means any downstream customizing such as setting a background image gets clobbered unnecessarily.

**Solution:** Unless Infima specifically _means_ to clobber any other background properties, it should just set the `background-color` when that's all that's being specified.

I'm happy to submit a PR for this, although I'm unsure if this is a change I should make everywhere I find it or just in that one instance. Guidance welcome!

**Comment by lex111** [comment]
Sorry for the delay, apparently it would have been better to fix it for this particular case for now, if you still want to do it, please let me know about it.

**Comment by reefdog** [comment]
@lex111 Happy to! Will issue a PR shortly.

**Comment by reefdog** [comment]
@lex111 Since this issue will affect other elements too, do you think it's worth keeping open until all instances are resolved?

**Comment by lex111** [comment]
I would keep this issue closed, but instead fixing each specific case if it arises. Although I understand that in general it's wrong to use `background` property for background color only, but it's a kind of micro-optimization.
