### ISSUE TITLE
Doc sidebar active category not highlighted

### ISSUE THREAD

**Issue by Josh-Cena** [facebookincubator/infima#202]
https://github.com/facebookincubator/infima/blob/8c592e4fad80d410fcb9ffb132e6b2efc70c9db4/packages/core/styles/components/menu.pcss#L88

This `!important` has prevented the category link from being highlighted.

![image](https://user-images.githubusercontent.com/55398995/150459623-ce1c0f50-7903-485b-90f3-4b6a61a811f2.png)

**Comment by lex111** [comment]
To achieve this, there is `menu__list-item-collapsible--active` class that needs to be set for the current active category.
It should be fixed in this PR https://github.com/facebook/docusaurus/pull/6531
