### ISSUE TITLE
SCSS rewrite proposal

### ISSUE THREAD

**Issue by RDIL** [facebookincubator/infima#226]
Copied from Discord:

I think that for Infima, we should possibly consider moving to something like SCSS instead of postcss.

Why:
- Current setup is highly opinionated, and frowned upon by the postcss core team
- It's not as easy to maintain as it probably could be
- It's difficult to build without adding lots of dependencies out of this repository

Pros:
- More widely supported toolchain, compilers for which are available in many different languages, e.g. sass and node-sass
- Could allow for enhanced treeshaking for projects like mine that use ifm outside Docusaurus.
- Better IDE support potentially

Cons:
- Rewriting of some syntax would be required
- It's a decently big shift

Let me know what y'all think.

**Comment by slorber** [comment]
IMHO nothing is blocking us in this repo from providing the value that we aim to provide to our end users. 

Refactoring everything just for the beauty of our setup is not really worth it unless to do so pre-emptively to avoid potential future blockers.

In any case, I'd prefer delaying this refactor after the 2.0 launch to avoid unnecessary distractions on something that could eventually become a time-sink.

> Could allow for enhanced treeshaking for projects like mine that use ifm outside Docusaurus.

That's the first time I hear Infima is used outside Docusaurus. 
I'm not sure it's a great idea personally and wonder what are your motivations.

**Comment by lex111** [comment]
We actually used SASS syntax before, but we originally also used PostCSS, so decided to limit the number of tools to use and get rid of SASS in the end.
Infima is a pretty small project, so PostCSS is very good for it. Maybe in the next major version migrating to SASS would be justified, but definitely not right now.

**Comment by RDIL** [comment]
@slorber I'm using it to design user interfaces that match the documentation which uses Docusaurus.

**Comment by RDIL** [comment]
Closing this as we now have an internal fork of Infima as of alpha 39.
