### ISSUE TITLE
Logo not loading in 'Multi-Column' example for footer

### ISSUE THREAD

**Issue by iammati** [facebookincubator/infima#239]
URL: https://infima.dev/docs/components/footer
The logo isn't loading and you guys may want to change the "2019" to something more dynamic in all three examples (Simple, Multi-Column and Dark) :)

PS: Logo also affects to the "Dark" section right below

![image](https://user-images.githubusercontent.com/41418763/163689062-18f29bf6-d687-46de-be73-4b017087d49b.png)

**Comment by Josh-Cena** [comment]
Thanks for the report. The broken image looks worth fixing, but the copyright is by design, because we are only demonstrating static markup.

There are two problems here: (1) we shouldn't use `src="img/fb-oss-dark.png"` because that's relative to the current URL instead of relative to the root (2) the image simply doesn't exist.

@yangshun Do you have the image for `fb-oss-dark.png`? I only have the version meant to be used on dark backgrounds.

**Comment by slorber** [comment]
I don't think I ever saw a variant supposed to be displayed on light background

also received new Meta assets from Joel and there's no asset to be displayed on light background either

This one is likely the one we'll start using in the future:

![Meta_lockup_negative_primary_RGB](https://user-images.githubusercontent.com/749374/164481121-88b89b69-56b6-4fe9-8ef3-7adccac53cec.png)

**Comment by slorber** [comment]
FYI those are all the pngs I got from Joel:
![Meta_lockup_positive_primary_RGB](https://user-images.githubusercontent.com/749374/164481485-14668f0a-a8d9-47cd-bd4c-105ff4b064a5.png)
![Meta_lockup_negative_primary_RGB](https://user-images.githubusercontent.com/749374/164481504-7bd9a883-e54d-4d7c-be1c-ef18ab6c9163.png)
![Meta_lockup_mono_black_RGB](https://user-images.githubusercontent.com/749374/164481514-1c95f3f1-8dbe-4f98-8053-ea6cfec14b0d.png)
![Meta_lockup_mono_white_RGB](https://user-images.githubusercontent.com/749374/164481520-6ac34d91-ceff-42bc-acc3-2ae5af28428d.png)

(Also have SVG/AI)

**Comment by Josh-Cena** [comment]
Geez these images are legit making my browser lag...

**Comment by iammati** [comment]
> Geez these images are legit making my browser lag...

Same here lol you guys should maybe investigate into that since those images shouldn't cause a browser to lag that much at all 🤣
btw I'm using Brave 1.38.111 Chromium: 101.0.4951.54 (official build) (64-bit)

**Comment by Josh-Cena** [comment]
Each of these images are ~2MB, and 29000px (!) wide, I'm not surprised

They'd better give SVGs directly...

**Comment by Josh-Cena** [comment]
I've collapsed the comment so we can take a breath

**Comment by Josh-Cena** [comment]
About fixing this issue, I will wait a while, because seems none of the other Facebook sites have changed yet (?), so I'm not sure which direction we are moving in

**Comment by iammati** [comment]
Alright. Thanks for taking care of that insane loading times, though quite hilarious
