### ISSUE TITLE
using docusaurus - problem with css from using it

### ISSUE THREAD

**Issue by UXDart** [facebookincubator/infima#257]
Hello! I'm working on a project using the source code of docusaurus (last version), I can add for example DocSidebar into my project, and use it, but the styles are missing. tried creating a rule css on webpack on the node_modules folder but is not taking css from it. I can see each component has new css classes like "styles-module___abcd" abcd changes every time. I assume it is infima that are generating those, but how can I use the css generated inside the docusaurus package in my project? Thanks!

**Comment by Josh-Cena** [comment]
Please see https://docusaurus.io/docs/styling-layout#global-styles

> - **Infima class names**. These class names are found in the classic theme and usually follow the [BEM convention](http://getbem.com/naming/) of `block__element--modifier`. They are usually stable but are still considered implementation details, so you should generally avoid targeting them. However, you can [modify Infima CSS variables](#styling-your-site-with-infima).
> - **CSS module class names**. These class names have a hash in production (`codeBlockContainer_RIuc`) and are appended with a long file path in development. They are considered implementation details and you should almost always avoid targeting them in your custom CSS. If you must, you can use an [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) (`[class*='codeBlockContainer']`) that ignores the hash.

"styles-module___abcd" is a CSS module class name and it's generated by the theme components' module CSS, not by Infima. Infima always generates stable BEM class names. If you are to target CSS module class names (you are strongly advised not to), you need to use `[class*=...]`.

I hope that answers your question; but I'm still going to close this as a question. We can continue to discuss on the Docusaurus Discord, or Docusaurus' Discord discussions. Issues here have very low visibility and don't help others with the same question.
