### ISSUE TITLE
Code sample for "active" Button include "outline" classes

### ISSUE THREAD

**Issue by jodyheavener** [facebookincubator/infima#273]
Small thing. I was looking through the [Button](https://infima.dev/docs/components/button) component variations and noticed that the "active" style's code samples include classes present in the "outline" style. For example:

```html
<button class="button button--outline button--active button--primary">
  Primary
</button>
```

Removing the `button--outline` class appears to retain the active style, any reason it should be left in there?

**Comment by sanketmunot** [comment]
Created a PR #279 
Can check for build here -> https://deploy-preview-279--infima.netlify.app/docs/components/button#active

Thanks !
