### ISSUE TITLE
Unability to navigate collapsed menu without JS

### ISSUE THREAD

**Issue by slorber** [facebookincubator/infima#36]
Currently on D2 it's not possible to "navigate" to a collapsed menu without JS enabled. 

This is probably not the most impactful enhancement we could make, but I think I read it's a goal to make the site usable without JS (or before js hydration).

![image](https://user-images.githubusercontent.com/749374/83543715-2012b700-a4fd-11ea-8e39-97eb26bdbfe3.png)

We could probably expand a collapsed menu item on :focus / :focus-within

**Comment by kimbaudi** [comment]
Hi, I discovered Docusaurus v2 a week ago and also discovered this project as well. I couldn't help but to comment on this. I also don't think it is possible to implement tree view collapsible menu without JS. Please take a look at <https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView> where they need JS. I think it would be better to just display an expanded tree view if JS is disabled. The user will not be able to expand/collapse menus, but they can still navigate the menu.

**Comment by slorber** [comment]
Related to https://github.com/facebook/docusaurus/issues/3030

I made a demo without js, using focus-within here: https://github.com/facebook/docusaurus/pull/3642#issuecomment-717184325

> I think it would be better to just display an expanded tree view if JS is disabled.

We don't want to force the user to have all users with an expanded tree view by default. This should rather only affect users that were not able to load our JS properly (network error, disabled js, older browser...)

**Comment by kimbaudi** [comment]
There are tradeoffs to either displaying an expanded tree view or using `:focus-within`. It really depends on the # of menu items and how deeply nested the submenus are. The problem I have with `:focus-within` is that it collapses previous menu items that I have focused on as soon as I focus on a different menu item. When I'm navigating the sidebar of a documentation, it really helps to see all the menu items (not just the one that I am focused on). This is especially true when I am looking at new documentation and am still unfamiliar with the menu. But I do understand why you also don't want to force users to have an expanded tree view.

**Comment by m-allanson** [comment]
I'd like to see this handled too. A pattern I've used is to default to all expanded, and then collapse the menus only when JS is available.

One way to do this is with a `script` tag straight after the opening tag of the menu. e.g.

```html
<ul id="nav">
  <script>
    document.getElementById("nav").classList.add("collapsed");
  </script>
  <!-- the rest of the menu markup follows here... -->
```

This prevents a flash of changing styles, because the browser applies the _collapsed_ styles very early in the rendering process. [Here's a full example on CodeSandbox](
https://codesandbox.io/s/great-flower-ufxv1?file=/index.html).

Another alternative might be using `<noscript>` tags to render a full expanded menu when JS is disabled.

The downside to both of these approaches - they do nothing to help against network errors or JS errors in the app code.

**Comment by slorber** [comment]
@m-allanson the goal for me is not really to handle the case for users having disabled the JS, but rather being able to have a decent UI even before JS loads and React hydrates. I want to somehow make the React hydration process a progressive enhancement of the experience instead of being a hard requirement. In the same way a Gatsby link can be clicked even before the React hydration and can still navigate.

So I don't think your solution would work apart for users with JS disabled.

Related: https://kryogenix.org/code/browser/everyonehasjs.html

**Comment by m-allanson** [comment]
@slorber That's a fair point. 

> Related: kryogenix.org/code/browser/everyonehasjs.html

This is great, bookmarked!

**Comment by m-allanson** [comment]
What if the `.menu__link--sublist` element linked to the first item in the sublist?

That would make all parts of the site navigable without JS, and wouldn't change any functionality once the JS is running.

Once you've navigated to a sublist page, the sidebar already displays other pages in that category. 

```diff
<ul class="menu__list">
  <li class="menu__list-item">
-    <a class="menu__link menu__link--sublist menu__link--active" href="#!"
+    <a class="menu__link menu__link--sublist menu__link--active" href="/docs/next/api/plugins"
      >Plugins</a
    >
    <ul class="menu__list">
      <li class="menu__list-item">
        <a
          aria-current="page"
          class="menu__link menu__link--active active"
          tabindex="0"
          href="/docs/next/api/plugins"
          >Plugins overview</a
        >
      </li>
      <li class="menu__list-item">
        <a
          class="menu__link"
          tabindex="0"
          href="/docs/next/api/plugins/@docusaurus/plugin-content-docs"
          >📦 plugin-content-docs</a
        >
      </li>
    </ul>
  </li>
</ul>
```

<img width="873" alt="Screenshot showing suggested changes on the Docusaurus site" src="https://user-images.githubusercontent.com/381801/106759207-625f3b80-662a-11eb-8a1b-385ff375014a.png">

For example try browsing [the Docusaurus Plugins pages](https://v2.docusaurus.io/docs/next/api/plugins) without JS. That part works well, but you can't get to the Themes section. This change would enable navigating through to a different category.

**Comment by slorber** [comment]
That's definitively a behavior that would allow navigating to category subitems.

We have an issue to support that: https://github.com/facebook/docusaurus/issues/2643

Let's figure if this issue is still useful after we support that feature.
But I think we may still want to allow keeping the existing category behavior (no link), so it can still be useful in such case to allow browsing subitems.

**Comment by m-allanson** [comment]
My thought was to make the clientside JS restore the `href=#!` link when hydrating.

This way the change would only apply when JS failed to load.

**Comment by slorber** [comment]
That looks like a nice trick, didn't think of that, worth giving it a try ;)

**Comment by slorber** [comment]
As we now render "lazy/partial sidebars" on Docusaurus SSR, I think this will never be implemented in Infima so I'm closing

See my comment here https://github.com/facebook/docusaurus/issues/3030#issuecomment-879952374

**Comment by slorber** [comment]
I implemented your suggestion as part of https://github.com/facebook/docusaurus/pull/5830 @m-allanson
Now the sidebar is partially rendered on the server and we can still navigate it entirely with JS disabled.
Test URL: https://deploy-preview-5830--docusaurus-2.netlify.app/docs/next/category/guides/
The only edge-case where we can't navigate with JS disabled is when a category has no subitems (which is a weird use-case anyway)
Let me know if you see any issue

**Comment by m-allanson** [comment]
Lovely stuff, thank you 🙏 It works great from this side.
