### ISSUE TITLE
Styles appearing differently in production vs. development

### ISSUE THREAD

**Issue by clairefro** [facebookincubator/infima#60]
We are using Infima with Docusuarus 2 and are seeing styles rendered differently in production vs. development.  (This may be more of a Docusaurus issue than Infima issue)

For example, our code block styling in development 
![image](https://user-images.githubusercontent.com/9841162/105640179-683a6d00-5e31-11eb-84a8-9319a24932ba.png)

vs. production 
![image](https://user-images.githubusercontent.com/9841162/105640191-7ee0c400-5e31-11eb-990d-e44924bb2a9a.png)

What might be causing this? Here is a link to our `custom.css` file 
https://github.com/redwoodjs/learn.redwoodjs.com/blob/master/src/css/custom.css

**Comment by clairefro** [comment]
I was able to resolve this by using class substring selectors, following: 
https://github.com/facebook/docusaurus/issues/3879#issuecomment-738998359

**Comment by slorber** [comment]
yes the classnames are auto generated so it might be complicated to target the element you want.

As part of the theme gallery I'd like to introduce a list of official class names that are meant to be targetted by custom CSS
