### ISSUE TITLE
lint-staged / stylelint does not catch missing Facebook copyright

### ISSUE THREAD

**Issue by slorber** [facebookincubator/infima#81]
When a missing copyright header is not found, `yarn workspace infima lint` should report an error, but it does not (while other lint rules work)

**Comment by Josh-Cena** [comment]
I've fixed this problem in Docusaurus. https://github.com/facebook/docusaurus/tree/main/packages/stylelint-copyright is now able to provide autofix for missing copyright. I've been unable to figure out how stylelint is set up in Infima though
